openapi: 3.0.1
info:
  title: depromeet
  description: description
  version: '@project.version@'
servers:
  - url: http://localhost:8085
    description: local
tags:
  - name: Member
    description: Member tag
paths:
  /api/v1/members:
    post:
      tags:
        - Member
      summary: save member
      description: saveMemberAPIDEfas
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberCreateRequestDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponseDto'
        '400':
          description: BAD REQUEST
        '404':
          description: NOT FOUND
        '500':
          description: INTERNAL SERVER ERROR
  /api/v1/members/{id}:
    get:
      tags:
        - Member
      operationId: findUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponseDto'
components:
  schemas:
    MemberCreateRequestDto:
      required: [ nickname ]
      type: object
      properties:
        nickname:
          type: string
        test:
          type: string
    MemberResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nickname:
          type: string
    BaseResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
