spring:
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  session.jdbc.initialize-schema: never
  profiles:
    active: default
    include:
      - data




###SWAGGER###
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    url: /openapi3.yml
    operations-sorter: alpha
    tags-sorter: alpha
    path: /
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**
server:
  port: 8080


security:
  jwt:
    token:
      validtime: ${TOKEN_VALIDTIME}
      secretkey: ${TOKEN_SECRETKEY}

google:
  user:
    uri: https://www.googleapis.com/oauth2/v1/userinfo#profile
kakao:
  user:
    uri: https://kapi.kakao.com/v2/user/me
