spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - data-local
  redis:
    host: localhost
    password:
    port: 16379

security:
  jwt:
    token:
      validtime:
        access: 31557600000
        refresh: 31557600000
      secretkey: ENC(hL8s+Y0aTusUISK+0EIsOsqZ0lAX9b75Lvr/ouhpY1eHkd0Obb1yyopeNPgmlv3NBfe70T75yArdavd+HkBp1IlJDoHijG6/)
google:
  host: https://www.googleapis.com/oauth2
  user:
    uri: /v2/userinfo#profile
kakao:
  host: https://kapi.kakao.com
  user:
    uri: /v2/user/me
  unlink:
    uri: /v1/user/unlink
  adminKey: ENC(4wC/jyuomP+b7iZ6kteY0nc5l+PZ6dX2DTvFR4ZKGO51KmBbxEcPNf5IrVD/nBeS)
firebase:
  multicast-message:
    size: 500
  projectId: project
  private:
    keyId: ENC(yG1+pvl3s30DCmWmfWplUgDQWgJ9bUZ2U0gZxDvE/GY8GsJ7DDbAkSRQICmLf5DdvoVlTtlWlGw=)
    key: ${FIREBASE_PRIVATE_KEY:#{null}}
  client:
    id: clientId
    email: clientEmail
  token:
    uri: https://oauth2.googleapis.com/token

batch:
  global: 30
  habit: 30

server:
  port: 8080
