spring:
  config:
    use-legacy-processing: true
  profiles:
    active: local
    include:
      - data-local
  redis:
    host: localhost
    password:
    port: 16379

##SOCIAL
google:
  access:
    token:
      uri: https://oauth2.googleapis.com/token
  user:
    uri: https://www.googleapis.com/oauth2/v1/userinfo
  web:
    redirect:
      uri: googleDummy
    client:
      id: googleDummy
      secret: googleDummy
