spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  session.jdbc.initialize-schema: never


###SWAGGER###
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    url: /openapi3.yml
    operations-sorter: alpha
    tags-sorter: alpha
    path: /
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**