spring:
  config:
    use-legacy-processing: true
  profiles:
    active: local
    include:
      - data-local
  redis:
    host: localhost
    password:
    port: 16379

security:
  jwt:
    token:
      validtime: 72000000