spring:
  config:
    use-legacy-processing: true
  profiles:
    active: local
    include:
      - data-local
  redis:
    host: localhost
    password:
    port: 16379

##SOCIAL
google:
  access:
    token:
      uri: googleDummy
  web:
    redirect:
      uri: googleDummy
    client:
      id: googleDummy
      secret: googleDummy
  user:
    uri: googleDummy