spring:
  config:
    use-legacy-processing: true
  profiles:
    active: local
    include:
      - data-local
  redis:
    host: localhost
    password:
    port: 16379


security:
  jwt:
    token:
      validtime: 72000000
      secretkey: 974AE3E91F2972E1BF2951CE1F651974AE3E91F2972E1BF2951CE1F651974AE3E91F2972E1BF2951CE1F651

google:
  user:
    uri: https://www.googleapis.com/oauth2/v1/userinfo#profile
