spring:
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  session.jdbc.initialize-schema: never
  profiles:
    active: default
    include:
      - data

###SWAGGER###
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    url: /openapi3.yml
    operations-sorter: alpha
    tags-sorter: alpha
    path: /
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**
server:
  port: 8080


security:
  jwt:
    token:
      validtime: ${TOKEN_VALIDTIME}
      secretkey: ${TOKEN_SECRETKEY}

google:
  host: https://www.googleapis.com/oauth2
  user:
    uri: /v2/userinfo#profile
kakao:
  host: https://kapi.kakao.com
  user:
    uri: /v2/user/me
  unlink:
    uri: /v1/user/unlink
  adminKey: ${KAKAO_ADMINKEY}

firebase:
  multicast-message:
    size: 500
  projectId: three-days-bd5f3
  private:
    keyId: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    id: 115789865759617169410
    email: firebase-adminsdk-v3brd@three-days-bd5f3.iam.gserviceaccount.com
  token:
    uri: https://oauth2.googleapis.com/token

batch:
  global: 30
  habit: 30
