spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - data-dev

security:
  jwt:
    token:
      validtime:
        access: 31557600000
        refresh: 31557600000
        clientSecret: 3600000
      secretkey: ${TOKEN_SECRETKEY}

google:
  host: https://www.googleapis.com/oauth2
  user:
    uri: /v2/userinfo#profile
kakao:
  host: https://kapi.kakao.com
  user:
    uri: /v2/user/me
  unlink:
    uri: /v1/user/unlink
  adminKey: ${KAKAO_ADMINKEY}
apple:
  serviceId: ${APPLE_SERVICE_ID}
  teamId: ${APPLE_TEAM_ID}
  keyId: ${APPLE_KEY_ID}
  host: ${APPLE_HOST}
  p8: ${APPLE_P8}
  key:
    uri: /auth/keys
  token:
    uri: /auth/token
  unlink:
    uri: /auth/revoke

firebase:
  multicast-message:
    size: 500
  projectId: three-days-develop
  private:
    keyId: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    id: ${FIREBASE_CLIENT_ID}
    email: ${FIREBASE_CLIENT_EMAIL}
  token:
    uri: https://oauth2.googleapis.com/token
