name: Java CI with Gradle

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
          ./gradlew build
    - name: Integration Test with Gradle
      run: |         
          docker-compose -f resources/local-develop-env/docker-compose.yml up -d
          sleep 20
          
          ./gradlew :data:flywayClean :data:flywayMigrate
          export SPRING_PROFILES_ACTIVE=integration-test
          
          ./gradlew integrationTest
